export const USER_LIST = "USERS/USER_LIST";
export const GET_USERS_SUCCESS = "USERS/GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "USERS/GET_USERS_FAIL";

export const EDIT_USER = "USERS/EDIT_USER";

export const GET_USER_SUCCESS = "USERS/GET_USER_SUCCESS";
export const GET_USER_FAIL = "USERS/GET_USER_FAIL";

export const UPDATE_USER = "USERS/UPDATE_USER";
export const UPDATE_USER_FAIL = "USERS/UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "USERS/UPDATE_USER_SUCCESS";
